"""Create a new TodoList data-model, add a new 'list_id' column to out Todo data-model

Revision ID: 6cc201f0ef25
Revises: b3af1f5344ca
Create Date: 2021-09-24 19:55:21.469913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc201f0ef25'
down_revision = 'b3af1f5344ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # start of manually adjusted commands
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.execute('''
        INSERT INTO todolists (title) VALUES ('TestList1');
        UPDATE todos SET list_id = 1 WHERE list_id IS NULL;
    ''')
    op.alter_column('todos', 'list_id', nullable=False)
    # end of manually adjusted commands

    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
