"""Add a new 'completed' column to our todo data-model

Revision ID: b3af1f5344ca
Revises: df105bbf085c
Create Date: 2021-09-22 21:18:52.660498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3af1f5344ca'
down_revision = 'df105bbf085c'
branch_labels = None
depends_on = None


def upgrade():
    # ### auto generated commands are replaced by the follwing commands ###
    # ### adjusted commands for the current database migration ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('''
        UPDATE todos SET completed = False WHERE completed IS NULL;
    ''')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
